package com.example.sunshine.enums.states;
public enum DataState {
  SUCCESS_GETTING_DATA,
  NULL_INPUT_STREAM,
  BLANK_INPUT_STREAM,
  CANNOT_CREATE_JSON,
  INVALID_JSON;
  public enum ParseJson {
    SUCCESS_PARSING_JSON_GENERAL_DATA,
    SUCCESS_PARSING_JSON_CURRENT_DATA,
    SUCCESS_PARSING_JSON_MINUTELY_DATA,
    SUCCESS_PARSING_JSON_HOURLY_DATA,
    SUCCESS_PARSING_JSON_DAILY_DATA,
    SUCCESS_PARSING_JSON_ALERT_DATA,
    SUCCESS_PARSING_JSON_RAW_DATA,
    CANNOT_PARSE_JSON_GENERAL_DATA,
    CANNOT_PARSE_JSON_CURRENT_DATA,
    CANNOT_PARSE_JSON_MINUTELY_DATA,
    CANNOT_PARSE_JSON_HOURLY_DATA,
    CANNOT_PARSE_JSON_DAILY_DATA,
    CANNOT_PARSE_JSON_ALERT_DATA,
    CANNOT_PARSE_JSON_RAW_DATA;
  }
}
